.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. smartcoin_qt test_smartcoin_qt
clean: FORCE
	$(MAKE) -C .. smartcoin_qt_clean test_smartcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_smartcoin_qt_check
smartcoin-qt smartcoin-qt.exe: FORCE
	 $(MAKE) -C .. smartcoin_qt
